# Chapter 3

1. 

In [2]:
import torch

In [3]:
pts = torch.tensor(list(range(9)))
pts

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
pts.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]

In [11]:
pts.shape

torch.Size([9])

In [12]:
pts.stride()

(1,)

1a)

In [14]:
b = pts.view(3,3) 
# view will create a reference to a, with changes to offset and stride, but not the 
# object in memory

In [15]:
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [16]:
b.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]

In [17]:
b.stride()

(3, 1)

In [18]:
b.storage_offset()

0

In [19]:
b.storage_type()

torch.LongStorage

1b)

In [20]:
c = b[1:, 1:]

In [21]:
# c will be a 2x2 matrix, with contents: [4,5],[7,8]

In [22]:
c

tensor([[4, 5],
        [7, 8]])

In [28]:
# what will the size be? size will be 9. WRONG! Size will be [2,2], i was thinking of storage. 
# since c is a view on b, and b is a view on pts, and pts is 9.

In [36]:
# note : .size and .shape are the samething

In [29]:
c.size()

torch.Size([2, 2])

In [35]:
c.shape

torch.Size([2, 2])

In [30]:
c.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]

In [31]:
# what will the stride and offset be? stride will be 2,1 and offset will be 4(?)

In [32]:
c.stride()

(3, 1)

In [37]:
# is the stride still from the 3x3 array we made?

In [34]:
c.storage_offset()

4

---

In [38]:
a = torch.tensor(list(range(9)))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
# size: 9x1 , storage: 0...9, offset: 0, stride: 1,
a.size(), a.storage(), a.storage_offset(), a.stride()

(torch.Size([9]),
  0
  1
  2
  3
  4
  5
  6
  7
  8
 [torch.LongStorage of size 9],
 0,
 (1,))

In [41]:
b = a.view(3,3)
# b = [[0,1,2], [3,4,5], [6,7,8]]
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [42]:
# size = [3,3]
# storage = 0,...,8
# offset = 0
# stride = 3,1
b.size(), b.storage(), b.storage_offset(), b.stride()

(torch.Size([3, 3]),
  0
  1
  2
  3
  4
  5
  6
  7
  8
 [torch.LongStorage of size 9],
 0,
 (3, 1))

In [43]:
c = b[1:, 1:]
# c = [ [4,5], [7,8]]
c

tensor([[4, 5],
        [7, 8]])

In [45]:
# size = 2x2
# storage = 0,...,8 b/c reference/view back to a
# offset = 3 --> it is 4 b/c: offset of 0 is starting, so offset of 4 will be the 4th entry as our start
# stride = 2,1 --> it's 3,1 b/c: I don't know. is it because the parent was 3,1?
c.size(), c.storage(), c.storage_offset(), c.stride()

(torch.Size([2, 2]),
  0
  1
  2
  3
  4
  5
  6
  7
  8
 [torch.LongStorage of size 9],
 4,
 (3, 1))

In [ ]:
import torch
a = torch.tensor(list(range(9)))
b = a.view(3,3)
c = b[1:, 1:]
c.size(), c.storage(), c.storage_offset(), c.stride()
# why is stride 3,1?

In [46]:
q = a.view(3,3)[:,:]
q

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [47]:
q.size(), q.storage(), q.storage_offset(), q.stride()

(torch.Size([3, 3]),
  0
  1
  2
  3
  4
  5
  6
  7
  8
 [torch.LongStorage of size 9],
 0,
 (3, 1))

In [48]:
2.

2.0

In [53]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
torch.sqrt(a)

RuntimeError: sqrt_vml_cpu not implemented for 'Long'

In [58]:
torch.cosh(torch.randn(3,3))

tensor([[1.0731, 3.0432, 1.2113],
        [1.8180, 1.4600, 1.0140],
        [1.0341, 1.1899, 1.2153]])

In [65]:
a.dtype

torch.int64

In [67]:
a = a.type(torch.float)

In [68]:
a.cosh()

tensor([1.0000e+00, 1.5431e+00, 3.7622e+00, 1.0068e+01, 2.7308e+01, 7.4210e+01,
        2.0172e+02, 5.4832e+02, 1.4905e+03])

In [69]:
a

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [70]:
for i,ent in enumerate(a):
    a[i] = torch.cosh(a[i])

In [71]:
a

tensor([1.0000e+00, 1.5431e+00, 3.7622e+00, 1.0068e+01, 2.7308e+01, 7.4210e+01,
        2.0172e+02, 5.4832e+02, 1.4905e+03])

In [72]:
torch.cosh_(a)

tensor([1.5431e+00, 2.4464e+00, 2.1533e+01, 1.1784e+04, 3.6206e+11, 8.4712e+31,
               inf,        inf,        inf])

In [73]:
a = torch.randn(3,3)
a

tensor([[ 0.3228,  0.5700, -0.3029],
        [-1.2365,  0.2564,  3.1068],
        [-0.8374, -0.7515, -0.0875]])

In [74]:
a.sqrt()

tensor([[0.5681, 0.7550,    nan],
        [   nan, 0.5063, 1.7626],
        [   nan,    nan,    nan]])

In [75]:
a

tensor([[ 0.3228,  0.5700, -0.3029],
        [-1.2365,  0.2564,  3.1068],
        [-0.8374, -0.7515, -0.0875]])

In [76]:
a.sqrt_()

tensor([[0.5681, 0.7550,    nan],
        [   nan, 0.5063, 1.7626],
        [   nan,    nan,    nan]])

In [77]:
a

tensor([[0.5681, 0.7550,    nan],
        [   nan, 0.5063, 1.7626],
        [   nan,    nan,    nan]])