# Chapter 5: Exercises

1. Redefine the model to be w2 * tu **2 + w1 * t_u + b

In [94]:
import torch
import numpy as np

In [95]:
t_c = [0.5,  14.0, 15.0, 28.0, 11.0,  8.0,  3.0, -4.0,  6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c = torch.tensor(t_c)
t_u = torch.tensor(t_u)

In [96]:
import matplotlib.pyplot as plt

In [97]:
t_unorm = t_u * 0.1

a) what parts of the training loop, and so on, need to be changed to accommodate the new model?

In [98]:
# i believe only the params part needs to be changed, let's rewrite our model from 
# increasing to decreasing order
# model = w0 + w1 * tu + w2 * tu^2
# our parameters are [w0, w1, w2]
# we can initialized them as [0.0, 1.0, 1.0]
# we will also redifine our model

In [109]:
def model(t_u, w0, w1, w2):
    return w0 + (w1 * t_u) + (w2 * t_u**2)

In [110]:
def loss_fn(t_p, t_c):
    """
    take the mean of all the squared difference, i.e. mean squared error
    
    t_p = prediction
    t_c = target / ground truth
    """
    squared_diffs = (t_p - t_c)**2
    return squared_diffs.mean()

In [142]:
# update training with optimizer
def training_optim(n_epochs, optimizer, params, t_u, t_c, print_params=True):
    """
    """
    for epoch in range(1, n_epochs+1):
        t_p = model(t_u, *params)
        loss = loss_fn(t_p, t_c)
        optimizer.zero_grad() # clear gradients
        loss.backward() # calculate gradient and propogate through network
        optimizer.step() # update all params
        
        if print_params==True and epoch % 500 == 0:
            print('epoch %d, loss %f' % (epoch, float(loss)))
    return params

In [143]:
import torch.optim as optim

In [144]:
params = torch.tensor([0.5, 0.2, 0.1], requires_grad=True) # w0, w1, w2
learning_rate = 1e-2
optimimzer = optim.Adam([params], lr=learning_rate)

In [145]:
training_optim(10000, optimizer=optimimzer, params=params, t_u=t_unorm, t_c=t_c)

epoch 500, loss 3.565741
epoch 1000, loss 3.042868
epoch 1500, loss 2.902088
epoch 2000, loss 2.742264
epoch 2500, loss 2.577302
epoch 3000, loss 2.422961
epoch 3500, loss 2.293494
epoch 4000, loss 2.198092
epoch 4500, loss 2.138147
epoch 5000, loss 2.107311
epoch 5500, loss 2.095014
epoch 6000, loss 2.091472
epoch 6500, loss 2.090801
epoch 7000, loss 2.090726
epoch 7500, loss 2.090721
epoch 8000, loss 2.090721
epoch 8500, loss 2.090721
epoch 9000, loss 2.090721
epoch 9500, loss 2.090721
epoch 10000, loss 2.090721


tensor([-10.6496,   2.4760,   0.2830], requires_grad=True)

In [146]:
params

tensor([-10.6496,   2.4760,   0.2830], requires_grad=True)

In [147]:
t_c

tensor([ 0.5000, 14.0000, 15.0000, 28.0000, 11.0000,  8.0000,  3.0000, -4.0000,
         6.0000, 13.0000, 21.0000])

In [148]:
model(t_unorm, *params)

tensor([ 1.7972, 12.0360, 13.3483, 28.6146, 12.2621,  8.2264,  0.9969, -3.9067,
         7.9649, 14.6315, 19.5288], grad_fn=<AddBackward0>)

b) what parts are agnostic to swapping out?

In [93]:
# the training loop and other parts remain the same, only the params and model definition change

c) is the resulting loss better or worse

In [151]:
# the error looks much worse when I use SGD, but using Adam seems to make it converge a bit but the result is still higher than the best result with a linear model

d) is the actual result better or worse

In [152]:
# worse. 