# Chapter 3

work/examples from the chapter

In [1]:
import torch

In [2]:
a = [1., 2., 3.]

In [3]:
type(a)

list

In [4]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
a[2] = 2.

In [7]:
a

tensor([1., 1., 2.])

suppose we want to store coordinates, (4,1), (5,3), and (2,1) we can do this in python or torch

In [8]:
points = torch.tensor([4.,1,5,3,2,1])
points

tensor([4., 1., 5., 3., 2., 1.])

we can also build a 2d tensor:

In [9]:
points = torch.tensor([[4.,1], [5,3], [2,1]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [10]:
points.shape

torch.Size([3, 2])

we can perform slicing as before

In [11]:
# get first row
points[0]

tensor([4., 1.])

In [12]:
# get first column
points[:,0]

tensor([4., 5., 2.])

In [13]:
# get 3. from the array
points[1,1]

tensor(3.)

In [14]:
# get 2. from array
points[2,0]

tensor(2.)

In [15]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [17]:
points.shape, points[None].shape

(torch.Size([3, 2]), torch.Size([1, 3, 2]))

In [18]:
img_t = torch.randn(3,5,5)
weights = torch.tensor([0.216, 0.715, 0.072])
batch_t = torch.randn(2,3,5,5)

In [20]:
# compute simple mean
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)

img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [21]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
unsqueezed_weights.shape, unsqueezed_weights

(torch.Size([3, 1, 1]),
 tensor([[[0.2160]],
 
         [[0.7150]],
 
         [[0.0720]]]))

In [24]:
weights.unsqueeze_?

Docstring:
unsqueeze_(dim) -> Tensor

In-place version of :meth:`~Tensor.unsqueeze`
Type:      builtin_function_or_method


In [25]:
img_weights = img_t * unsqueezed_weights
batch_weights = batch_t * unsqueezed_weights

In [26]:
batch_weights.shape, batch_t.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]))

In [27]:
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)

Named Tensors

In [28]:
img_named = img_t.refine_names(...,'channels', 'rows', 'columns')
img_named

/opt/conda/conda-bld/pytorch_1587428270644/work/c10/core/TensorImpl.h:806: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable.


tensor([[[-0.8987, -0.2165,  0.6534,  0.1293, -0.0560],
         [-1.9278,  0.0305, -0.4811, -2.0761, -0.5845],
         [ 0.4023, -1.3414,  1.5949,  0.6018, -0.2240],
         [-0.8657, -1.8551, -1.2617, -0.7341,  0.8487],
         [-3.2817, -0.6576, -0.4142, -0.0515, -0.3089]],

        [[-0.5991, -1.1810,  0.4190,  1.4225,  0.7963],
         [ 0.8161, -1.1719,  1.2742, -0.2548,  0.3081],
         [-0.1859, -0.8101, -0.5885, -0.6740, -0.9959],
         [ 1.8563, -1.9160,  0.9693, -1.8966, -0.1133],
         [-0.8112, -0.5262, -0.1251,  0.1150, -1.2068]],

        [[-0.2835, -1.2424,  0.1029, -0.2563,  1.4648],
         [ 0.8653,  0.5513,  0.2436, -0.3286,  1.7678],
         [ 0.4358, -0.8752, -0.0037,  2.1723,  0.1546],
         [-1.0752,  0.0195,  1.3972, -0.4637, -0.4750],
         [ 0.4274,  0.8484,  0.2325,  0.2194,  0.0511]]],
       names=('channels', 'rows', 'columns'))

In [30]:
batch_named = batch_t.refine_names(...,'channels', 'rows', 'columns')
batch_named

tensor([[[[-2.0707, -0.4983,  1.0842, -1.0241,  0.6168],
          [ 0.0318, -0.5902,  0.3892,  0.2965,  0.5705],
          [-0.9010,  0.4486, -1.1571, -0.4534, -1.6583],
          [ 0.2295,  1.5762,  1.8695,  0.4109, -0.4839],
          [ 1.0048, -1.1989,  0.7378,  1.0575, -1.3614]],

         [[ 0.3529,  1.0490,  0.8558, -0.0681, -0.2465],
          [ 1.4298,  0.1088,  0.2936, -0.3939,  2.3839],
          [-0.5454,  1.0236, -0.7513,  1.9965, -0.4507],
          [ 0.4266, -1.5037,  1.1497,  1.2056,  0.2309],
          [ 0.4313, -0.4163,  1.1136,  0.0442, -1.0819]],

         [[ 0.0318,  1.9646, -0.1475,  0.2850, -0.4969],
          [-0.5147,  1.0956,  0.7914,  1.2931,  1.2901],
          [ 0.5463, -0.4259, -0.7810,  0.6408,  0.0798],
          [ 0.7977,  0.3035, -1.5389, -1.4599, -0.6217],
          [-0.2767, -0.3982, -0.6701,  0.5319,  0.1443]]],


        [[[ 0.6420, -0.2329,  0.0031,  1.9364, -0.4262],
          [ 0.6301, -1.3914,  0.8555, -0.2027, -0.0368],
          [-0.3757, -0.

In [32]:
weights_named = weights.refine_names('channels')
weights_aligned = weights_named.align_as(img_named)
weights_aligned

tensor([[[0.2160]],

        [[0.7150]],

        [[0.0720]]], names=('channels', 'rows', 'columns'))

In [33]:
weights_aligned.rename(None)

tensor([[[0.2160]],

        [[0.7150]],

        [[0.0720]]])

Manipulations via `storage()`

In [35]:
points = torch.tensor([[1,2], [3,4]])
points

tensor([[1, 2],
        [3, 4]])

In [36]:
points.storage()

 1
 2
 3
 4
[torch.LongStorage of size 4]

In [37]:
points.storage()[2] = 88

In [38]:
points.storage()

 1
 2
 88
 4
[torch.LongStorage of size 4]

In [39]:
points

tensor([[ 1,  2],
        [88,  4]])

In place manipulations

In [40]:
points = torch.tensor([[1,2],[3,4]])
points

tensor([[1, 2],
        [3, 4]])

In [41]:
points.zero_()

tensor([[0, 0],
        [0, 0]])

In [42]:
points

tensor([[0, 0],
        [0, 0]])

Size, Offset and Stride

In [44]:
points = torch.tensor([ [4,0], [5,3], [2,1]])
points

tensor([[4, 0],
        [5, 3],
        [2, 1]])

In [45]:
item = points[2]
item

tensor([2, 1])

In [46]:
item.storage_offset()

4

In [47]:
points.stride()

(2, 1)

clones 

In [48]:
points 

tensor([[4, 0],
        [5, 3],
        [2, 1]])

In [49]:
sec_point_clone = points[1].clone()
sec_point_clone

tensor([5, 3])

In [50]:
sec_point_clone[0] = 88
sec_point_clone

tensor([88,  3])

In [51]:
points

tensor([[4, 0],
        [5, 3],
        [2, 1]])

In [52]:
# without clone

In [53]:
sec_point = points[1]
sec_point

tensor([5, 3])

In [54]:
sec_point[0] = 88
sec_point

tensor([88,  3])

In [55]:
points

tensor([[ 4,  0],
        [88,  3],
        [ 2,  1]])