# Chapter 3

work/examples from the chapter

In [1]:
import torch

In [2]:
a = [1., 2., 3.]

In [3]:
type(a)

list

In [4]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
a[2] = 2.

In [7]:
a

tensor([1., 1., 2.])

suppose we want to store coordinates, (4,1), (5,3), and (2,1) we can do this in python or torch

In [8]:
points = torch.tensor([4.,1,5,3,2,1])
points

tensor([4., 1., 5., 3., 2., 1.])

we can also build a 2d tensor:

In [9]:
points = torch.tensor([[4.,1], [5,3], [2,1]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [10]:
points.shape

torch.Size([3, 2])

we can perform slicing as before

In [11]:
# get first row
points[0]

tensor([4., 1.])

In [12]:
# get first column
points[:,0]

tensor([4., 5., 2.])

In [13]:
# get 3. from the array
points[1,1]

tensor(3.)

In [14]:
# get 2. from array
points[2,0]

tensor(2.)

In [15]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [16]:
points.shape, points[None].shape

(torch.Size([3, 2]), torch.Size([1, 3, 2]))

In [17]:
img_t = torch.randn(3,5,5)
weights = torch.tensor([0.216, 0.715, 0.072])
batch_t = torch.randn(2,3,5,5)

In [18]:
# compute simple mean
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)

img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [19]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
unsqueezed_weights.shape, unsqueezed_weights

(torch.Size([3, 1, 1]),
 tensor([[[0.2160]],
 
         [[0.7150]],
 
         [[0.0720]]]))

In [20]:
weights.unsqueeze_?

Docstring:
unsqueeze_(dim) -> Tensor

In-place version of :meth:`~Tensor.unsqueeze`
Type:      builtin_function_or_method


In [21]:
img_weights = img_t * unsqueezed_weights
batch_weights = batch_t * unsqueezed_weights

In [22]:
batch_weights.shape, batch_t.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]))

In [23]:
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)

Named Tensors

In [24]:
img_named = img_t.refine_names(...,'channels', 'rows', 'columns')
img_named

/opt/conda/conda-bld/pytorch_1587428270644/work/c10/core/TensorImpl.h:806: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable.


tensor([[[-0.2846, -1.2952, -1.4959,  1.6658, -1.2912],
         [ 0.2557, -0.1378,  0.2523, -0.4455,  0.0164],
         [-0.9158, -0.5512,  0.5588,  0.3612,  0.9303],
         [ 1.7731,  0.3456,  1.6754,  1.6764, -1.5007],
         [ 0.3761, -0.0971,  0.7862, -1.1254,  0.6666]],

        [[-0.8219, -0.2256,  0.4927,  2.1102, -0.6781],
         [-2.1942, -0.8367,  0.1410,  0.5888, -0.4120],
         [ 2.1856, -0.4421, -1.0460,  0.3201,  0.9168],
         [-1.2884,  1.1170,  0.9986, -0.3776,  2.2567],
         [ 0.6026,  0.7155, -1.2588, -0.5918,  1.0024]],

        [[-0.3773,  2.0649, -1.2724,  1.4562,  1.2798],
         [-1.3310, -1.1846, -0.4225,  0.1238,  1.3361],
         [ 0.3078, -1.2521, -1.3050, -0.2004,  0.5333],
         [-0.7146, -0.3555, -0.2238, -0.8089, -0.7092],
         [-1.9019, -1.0573,  0.4394, -0.0899,  1.7376]]],
       names=('channels', 'rows', 'columns'))

In [25]:
batch_named = batch_t.refine_names(...,'channels', 'rows', 'columns')
batch_named

tensor([[[[ 0.8001,  0.0513, -0.9721,  0.7298,  0.2797],
          [-0.3929,  1.3461,  1.4042, -0.9119,  0.8370],
          [ 0.0533,  1.7662, -0.9958, -0.7703,  1.1738],
          [ 0.9868, -1.4104,  1.0098,  1.2114, -0.3012],
          [ 0.2239,  1.1221, -1.8171, -1.2050,  0.4747]],

         [[ 1.1207, -0.3936,  0.6243,  0.6665,  0.9496],
          [ 1.6454,  0.1681, -2.4620,  0.7102, -0.8682],
          [-0.7439, -1.9291, -0.7747, -0.2245,  0.7474],
          [ 1.3345,  2.3048,  1.5906, -0.5342, -1.3575],
          [ 0.1298, -1.0554, -0.4913, -0.4917, -1.4534]],

         [[-0.4681,  0.3846,  0.1608,  0.4336,  1.0346],
          [ 0.7394, -0.3887, -0.4017, -0.6675,  0.3742],
          [ 0.7889, -0.2046,  0.0865,  0.9933, -0.8694],
          [-0.2359,  0.8463, -1.0780, -0.4920,  1.5773],
          [ 1.9852, -1.3368,  0.0799, -0.5317,  1.6674]]],


        [[[-0.7882, -1.6934, -0.4245,  0.0134,  0.1043],
          [ 0.9158,  0.0688, -0.4454,  0.3229,  1.0229],
          [-1.1905, -0.

In [26]:
weights_named = weights.refine_names('channels')
weights_aligned = weights_named.align_as(img_named)
weights_aligned

tensor([[[0.2160]],

        [[0.7150]],

        [[0.0720]]], names=('channels', 'rows', 'columns'))

In [27]:
weights_aligned.rename(None)

tensor([[[0.2160]],

        [[0.7150]],

        [[0.0720]]])

Manipulations via `storage()`

In [28]:
points = torch.tensor([[1,2], [3,4]])
points

tensor([[1, 2],
        [3, 4]])

In [29]:
points.storage()

 1
 2
 3
 4
[torch.LongStorage of size 4]

In [30]:
points.storage()[2] = 88

In [31]:
points.storage()

 1
 2
 88
 4
[torch.LongStorage of size 4]

In [32]:
points

tensor([[ 1,  2],
        [88,  4]])

In place manipulations

In [33]:
points = torch.tensor([[1,2],[3,4]])
points

tensor([[1, 2],
        [3, 4]])

In [34]:
points.zero_()

tensor([[0, 0],
        [0, 0]])

In [35]:
points

tensor([[0, 0],
        [0, 0]])

Size, Offset and Stride

In [36]:
points = torch.tensor([ [4,0], [5,3], [2,1]])
points

tensor([[4, 0],
        [5, 3],
        [2, 1]])

In [37]:
item = points[2]
item

tensor([2, 1])

In [38]:
item.storage_offset()

4

In [39]:
points.stride()

(2, 1)

clones 

In [40]:
points 

tensor([[4, 0],
        [5, 3],
        [2, 1]])

In [41]:
sec_point_clone = points[1].clone()
sec_point_clone

tensor([5, 3])

In [42]:
sec_point_clone[0] = 88
sec_point_clone

tensor([88,  3])

In [43]:
points

tensor([[4, 0],
        [5, 3],
        [2, 1]])

In [44]:
# without clone

In [45]:
sec_point = points[1]
sec_point

tensor([5, 3])

In [46]:
sec_point[0] = 88
sec_point

tensor([88,  3])

In [47]:
points

tensor([[ 4,  0],
        [88,  3],
        [ 2,  1]])

Contiguous in memory

In [48]:
points

tensor([[ 4,  0],
        [88,  3],
        [ 2,  1]])

In [49]:
points.is_contiguous()

True

In [51]:
points.t_()

tensor([[ 4, 88,  2],
        [ 0,  3,  1]])

In [52]:
points

tensor([[ 4, 88,  2],
        [ 0,  3,  1]])

In [53]:
points.is_contiguous()

False

In [56]:
points = points.contiguous()

In [57]:
points.is_contiguous()

True

Assignment to GPUs

In [59]:
!nvidia-smi

Thu May 27 19:24:39 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   36C    P0    64W / 250W |      0MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   34C    P0    39W / 260W |      0MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
        

nothing!

In [60]:
points

tensor([[ 4, 88,  2],
        [ 0,  3,  1]])

In [61]:
points = points.to(device='cuda')

In [62]:
!nvidia-smi

Thu May 27 19:25:10 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   36C    P2    64W / 250W |    722MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   35C    P0    62W / 260W |     11MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
        

In [63]:
points2 = points.clone()

In [64]:
points2 = points2.to(device='cuda:1')

In [65]:
!nvidia-smi

Thu May 27 19:25:56 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   36C    P2    64W / 250W |    722MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   34C    P2    62W / 260W |    722MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
        

:)

In [66]:
points_cpu = torch.tensor([[1.,2],[3,4],[5,6]])
points_cpu

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [67]:
points_gpu1 = points_cpu.clone().cuda(0)

In [68]:
!nvidia-smi

Thu May 27 19:27:45 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   35C    P2    64W / 250W |    722MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   33C    P8    25W / 260W |    722MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
        

In [69]:
points_gpu2 = points_cpu.clone().cuda(1)

Clearing GPU memory?!?

In [70]:
del points_gpu1
del points_gpu2
del points
del points2

In [71]:
!nvidia-smi

Thu May 27 19:29:40 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   33C    P8    19W / 250W |    722MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   33C    P8    25W / 260W |    722MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
        

In [72]:
torch.cuda.empty_cache()

In [74]:
!nvidia-smi

Thu May 27 19:31:31 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   33C    P8    20W / 250W |    722MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   32C    P8    24W / 260W |    722MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
        

hmmm... 

kill kernel here, and try again...

In [1]:
!nvidia-smi

Thu May 27 19:32:13 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   35C    P0    64W / 250W |      0MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   33C    P0    39W / 260W |      0MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
        

In [2]:
import torch

In [3]:
points = torch.tensor([[1,2], [3,4], [5,6]], device='cuda:0')

In [4]:
!nvidia-smi

Thu May 27 19:32:59 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   36C    P2    64W / 250W |    722MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   34C    P0    62W / 260W |     11MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
        

In [5]:
del points

In [6]:
!nvidia-smi

Thu May 27 19:33:09 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   36C    P2    64W / 250W |    722MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   33C    P8    24W / 260W |     11MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
        

In [7]:
torch.cuda.empty_cache()

In [8]:
!nvidia-smi

Thu May 27 19:33:44 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   34C    P8    20W / 250W |    720MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   33C    P8    24W / 260W |     11MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
        

**note** Memory usage did go down from 711mb to 709mb. Guess that is something. 